name: The Shiny Way
favicon: null
layout_spectrum: 0.7086903913877904
typography_spectrum: 0.7450960997957736
title: The Shiny Way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#ffb314'
    - '#f7fbf2'
    - '#bf0712'
    - '#76abe4'
  brandStrength: 0.16630730987526476
  lightness: 0.10892603173851967
  saturation: 0.29103987175039947
  rhythmicContrast: 0
purpose: []
